apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app2
  labels:
    app: app2
spec:
  # Project description
  description: Our ArgoCD Project to deploy our app locally
  # Allow manifests to deploy only from Sokube git repositories
  sourceRepos:
  - "https://github.com/mariav7/dnieto-c"
  # Only permit to deploy applications in the same cluster
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false